package uy.pensiones.enums;

/** Tipos de entidad referenciables por la bitácora administrativa. */
public enum AdminAuditEntityType {
    PENSION,
    MARKETPLACE_USER,
    REPORT,
    BACKOFFICE_USER,
    STUDY_CENTER,
    PLAN,
    PLAN_VERSION,
    OWNER_TRIAL_SETTINGS,
    PROMOTION_PRODUCT,
    PROMOTION_PRODUCT_VERSION,
    SUBSCRIPTION,
    PROMOTION,
    PAYMENT,
    PAYMENT_REFUND,
    PAYMENT_CHARGEBACK,
    PAYMENT_SETTINGS,
    PAYMENT_PROVIDER,
    PAYMENT_PROVIDER_EVENT,
    PAYMENT_RECONCILIATION_RUN,
    PAYMENT_PROVIDER_CERTIFICATION,
    LAUNCH_CAMPAIGN,
    LAUNCH_CAMPAIGN_BENEFICIARY
}
