package uy.pensiones.enums;

public enum NotificationType {
    INQUIRY_RECEIVED,
    INQUIRY_STATUS_CHANGED,
    INQUIRY_MESSAGE_RECEIVED,
    INVITE_RECEIVED,
    INVITE_ACCEPTED,
    MEMBER_REMOVED,
    MODERATION_PENSION_PAUSED,
    MODERATION_WARNING,
    MODERATION_HOLD_RELEASED,
    PENSION_AVAILABILITY_REVIEW_DUE,
    PENSION_AVAILABILITY_STALE,
    PENSION_AVAILABILITY_HIDDEN,
    PENSION_DRAFT_REMINDER,
    FOUNDER_BENEFIT_EXPIRING,
    FOUNDER_BENEFIT_EXPIRED,
    OWNER_TRIAL_STARTED,
    OWNER_TRIAL_EXPIRING,
    OWNER_TRIAL_GRACE,
    OWNER_ACCESS_PAUSED
}
