package uy.pensiones.enums;

public enum PaymentProviderCertificationCheckCode {
    SANDBOX_ORDER_WEBHOOK_CONFIGURED,
    SANDBOX_CHARGEBACK_WEBHOOK_CONFIGURED,
    PRODUCTION_CREDENTIALS_ACTIVATED,
    PRODUCTION_ORDER_WEBHOOK_CONFIGURED,
    PRODUCTION_CHARGEBACK_WEBHOOK_CONFIGURED
}
